### ISSUE TITLE
Add support for Crawl-Delay from robots.txt

### ISSUE THREAD

**Issue by pypt** [GateNLP/ultimate-sitemap-parser#1]
https://en.wikipedia.org/wiki/Robots_exclusion_standard#Crawl-delay_directive

**Comment by gavishpoddar** [comment]
Hi @pypt is the issue still open, If yes I would love to fix it

**Comment by freddyheppell** [comment]
I've decided not to implement this currently. The Crawl-Delay directive is arguably intended to set how frequently robots hit actual site pages. This library only runs with human intervention and only hits sitemaps/feeds. 

Instead I'll add implementing manual delays to the v1.1 roadmap (#49)
