### ISSUE TITLE
Throwing Exception while parsing date

### ISSUE THREAD

**Issue by malhotraguy** [GateNLP/ultimate-sitemap-parser#22]
Throwing unknown string format: null error while parsing the date.
URL used: https://www.ey.com/en_gl
For better reference traceback snapshot: 
![Screenshot from 2020-07-24 03-22-27](https://user-images.githubusercontent.com/34952205/88368913-f3d92100-cd5c-11ea-9c15-383df952128f.png)
![Screenshot from 2020-07-24 03-23-54](https://user-images.githubusercontent.com/34952205/88369033-297e0a00-cd5d-11ea-94b9-fb6bc8add1fb.png)

**Comment by pypt** [comment]
Thanks, I'll have a look. PRs (e.g. a simple `try-catch` around `dateutil_parse()`) are welcome too!
