### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by Pikamander2** [GateNLP/ultimate-sitemap-parser#25]
Is there a way to turn off logging? A single call to `sitemap_tree_for_homepage` spits out over 20 messages into the console, most of which are of no concern.

**Comment by StefanDjurovic** [comment]
Well, currently there is not.

**Comment by olirice** [comment]
Once `usp` is imported you can increase the loglevel to remove the `info` output like this

```
import logging
from usp.tree import sitemap_tree_for_homepage

logging.getLogger('usp.fetch_parse').setLevel(logging.WARN)
logging.getLogger('usp.helpers').setLevel(logging.WARN)
```

**Comment by sibalzer** [comment]
You can set the logger level to warning to ignore unnecessary messages.

```
logging.getLogger("usp.fetch_parse").setLevel(logging.WARNING)
logging.getLogger("usp.helpers").setLevel(logging.WARNING)
```

**Comment by ThibTrip** [comment]
> ```
> logging.getLogger("usp.fetch_parse").setLevel(logging.WARNING)
> logging.getLogger("usp.helpers").setLevel(logging.WARNING)
> ```

Thank you for your answer but this does not seem to work 😿.


# Example code

```python
import logging
from usp.tree import sitemap_tree_for_homepage

logging.getLogger("usp.fetch_parse").setLevel(logging.WARNING)
logging.getLogger("usp.helpers").setLevel(logging.WARNING)
logging.getLogger("usp.tree").setLevel(logging.WARNING)

sitemap_tree_for_homepage('https://www.siemens.de/')
```

```
2021-05-21 11:29:27,202 WARNING usp.helpers [1407409/MainThread]: Request for URL https://www.siemens.de/robots.txt failed: 404 Not Found
2021-05-21 11:29:27,829 WARNING usp.helpers [1407409/MainThread]: Request for URL https://www.siemens.de/sitemap-index.xml.gz failed: 404 Not Found
2021-05-21 11:29:28,443 WARNING usp.helpers [1407409/MainThread]: Request for URL https://www.siemens.de/sitemap_index.xml failed: 404 Not Found
2021-05-21 11:29:29,067 WARNING usp.helpers [1407409/MainThread]: Request for URL https://www.siemens.de/.sitemap.xml failed: 404 Not Found
2021-05-21 11:29:29,694 WARNING usp.helpers [1407409/MainThread]: Request for URL https://www.siemens.de/sitemap/sitemap-index.xml failed: 404 Not Found
2021-05-21 11:29:30,303 WARNING usp.helpers [1407409/MainThread]: Request for URL https://www.siemens.de/sitemap.xml failed: 404 Not Found
...
```

**Comment by sibalzer** [comment]
Thats because you are getting warning messages. If you want to ignore them too you need to set the logging level higher (`logging.ERROR` or even `logging.FATAL`). But i wouldn't recommend it.

**Comment by Pikamander2** [comment]
Ideally, it would be nice to have an official setting to suppress the output.

**Comment by freddyheppell** [comment]
Fixed in e252b43

**Comment by havardox** [comment]
Here's how to disable every single logger for literally every single USP module and for modules used by USP:

loggers = [
    "usp.web_client.requests_client",
    "usp.web_client",
    "charset_normalizer",
    "usp.helpers",
    "usp.tree",
    "urllib3.connection",
    "usp",
    "requests",
    "urllib3.connectionpool",
    "urllib3.util",
    "urllib3",
    "usp.fetch_parse",
    "urllib3.util.retry",
    "urllib3.poolmanager",
    "urllib3.response",
]

for logger_name in loggers:
    logging.getLogger(logger_name).disabled = True

**Comment by freddyheppell** [comment]
Theoretically, you should just be able to disable logging for the top level module (i.e. `usp`, `urllib3`, etc) and it gets inherited by child modules. If this doesn't work please open an issue!
