### ISSUE TITLE
How to set timeout properly 

### ISSUE THREAD

**Issue by ebauch** [GateNLP/ultimate-sitemap-parser#30]
Hi Team - thanks for this great lib! I have a couple of websites on my list that seem to be down. However, usp doesn't time out until like 2 hours later. How can I set the timeout to some shorter value for unresponsive websites? I did see the `set_timeout` parameter for the `web_client` class but not exactly sure how to initiate a web_client class with a proper timeout set. 

Here is how far I have come: 

```
from usp.web_client.requests_client import AbstractWebClient
from usp.web_client.requests_client import RequestsWebClient

RequestsWebClient.set_timeout(RequestsWebClient, timeout=10)
RequestsWebClient.set_max_response_data_length(RequestsWebClient, max_response_data_length=None)
web_client = RequestsWebClient

sitemap_tree_for_homepage('https://garfieldre2.org/', web_client=web_client)

```
which results in the following error. 

![image](https://user-images.githubusercontent.com/3758223/155449043-1bfa7529-1eb8-4bab-9c20-597e9eb5f6a5.png)

**Comment by fjfricke** [comment]
same issue here

**Comment by freddyheppell** [comment]
Timeout/max data length appear to work fine, but they are being set wrong in your code example.

The correct code would be:

```py

web_client = RequestsWebClient()
web_client.set_timeout(10)
```

Make sure to check the [requests docs on timeouts](https://requests.readthedocs.io/en/latest/user/advanced/#timeouts), particularly that the integer value set is used for 2 different timeouts, i.e. setting it to 10s means requests could take up to 20.

In the next version the docs will be updated to clarify this and officially support setting a tuple as well.
