### ISSUE TITLE
SSL Certificate error fix?

### ISSUE THREAD

**Issue by ma26yank** [GateNLP/ultimate-sitemap-parser#33]
I was testing this package for a web crawler I was building. But at times it gives below error. Is there any argument I have to pass or is this a bug?

_IndexWebsiteSitemap(url=https://www.crummy.com/, sub_sitemaps=[InvalidSitemap(url=https://www.crummy.com/robots.txt, reason=Unable to fetch sitemap from https://www.crummy.com/robots.txt: HTTPSConnectionPool(host='www.crummy.com', port=443): Max retries exceeded with url: /robots.txt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)'))))])_

what I am trying is: 

```
from usp.tree import sitemap_tree_for_homepage
tree = sitemap_tree_for_homepage("https://www.crummy.com")
print(tree)
```

**Comment by japherwocky** [comment]
You can subclass your own [RequestsWebClient](https://ultimate-sitemap-parser.readthedocs.io/en/latest/_modules/usp/web_client/requests_client.html#RequestsWebClient), and in particular in the [get method](https://ultimate-sitemap-parser.readthedocs.io/en/latest/usp.web_client.html#usp.web_client.requests_client.RequestsWebClient.get) use `requests.get( ... , verify=False)`
