### ISSUE TITLE
Authentication Method for Secured Sites?

### ISSUE THREAD

**Issue by ma26yank** [GateNLP/ultimate-sitemap-parser#34]
Hi, 
First of all, Thank you for building such a fantastic library for searching sitemaps through a website. There is a enhancement though which I would like to propose. 

I have noticed for one of the site when I was trying the same thing, it asks for authentication via HttpNtlmAuth. 

I was wondering if such arguments can be passed along with url to bypass authentication?

thanks

**Comment by freddyheppell** [comment]
HTTP auth, particularly NTLM auth, feels a little too niche for a library designed to crawl sitemaps (which should theoretically be public). The best way to handle this is probably to subclass the RequestsWebClient.
