### ISSUE TITLE
If `Content-Type` header is set, verify it's the expected one

### ISSUE THREAD

**Issue by pypt** [GateNLP/ultimate-sitemap-parser#4]
For example, if `Content-Type` for `/robots.txt` is `text/html` (and not `text/plain`), this usually means that the file is missing (and instead a 404 page would get returned) so there's no need to attempt to parse it.

Same goes for XML files, plain text sitemaps, and gzipped XML / text sitemaps.

**Comment by tanweeralii** [comment]
Hey pypt, I am a beginner here and I am looking for an good first issue. Seems this issue is good to start with. 
I have compiled and build it in my system. Now can you just brief more about this issue like how to solve. Thanks

**Comment by freddyheppell** [comment]
I would rather things were parsed in the most flexible way possible, and it's conceivable misconfigured servers may return the wrong mime type (and this seems more likely than a 404 page happening to contain valid robots.txt sitemap declarations).
