### ISSUE TITLE
End of Support 

### ISSUE THREAD

**Issue by pgulley** [GateNLP/ultimate-sitemap-parser#41]
Since this project has been left by the wayside for the last good chunk of time, the Mediacloud team has decided to formally end our support for the ultimate-sitemap-parser.  
As there are several active forks of this project, we wanted to give some lead time to figure out if any community members might be interested in assuming ownership of this repository and the associated package on pypi. This thread can be a place to figure out those details. 
Otherwise, in the beginning of September 2024, this repository will be archived.

**Comment by pgulley** [comment]
@JermellB, @antonialoytorrens-ikaue, @palverdata - you three have the most recently active forks.

**Comment by JermellB** [comment]
What are you guys using to parse sitemaps now?

**Comment by freddyheppell** [comment]
Hey, I'm a user of USP and a researcher in the GATE team at the University of Sheffield - I'm also the maintainer of the conda-forge recipe for this package. I/We may be able to take over maintaining this package.

I use this package as part of my research, so if it were just abandoned I'd probably end up having to fork and maintain it anyway!

I already maintain one package for my research called [wpextract](https://github.com/gatenlp/wpextract), which is partially based on another abandoned tool, so I have a bit of experience with this.  I'd be able to put in enough time initially to sort out the current state of the project (modernise packaging/CI and sort open issues/PRs) and a level of ongoing maintenance to keep things working.

Let me know if this would be of interest :) 


By the looks of things, sitemap-tools is intended to be a bit simpler (and not publicly packaged), so probably wouldn't be suitable for us or most USP users.

**Comment by pgulley** [comment]
@freddyheppell It sounds like you're exactly who we were hoping to find! I'll discuss with our team, but I think that soundsl like a good plan. 

Yes, sitemap-tools is not meant to replace USP in general, we have an emerging internal need for a nimbler package than USP but don't plan on formally packaging it.

**Comment by freddyheppell** [comment]
I've discussed this with our team's head and can confirm we're happy to take over maintenance of the package. We'd host the repo in our GH org, I'd be primarily responsible for maintenance, and I'd be able to spend some of my funded time on it when needed.

@pgulley: If you need to discuss any further details, feel free to drop me an email at f.heppell@sheffield.ac.uk
